### ISSUE TITLE
Possibility to give depth map in healsparse format

### ISSUE THREAD

**Issue by marina-ricci** [LSSTDESC/clevar#112]
At the moment, the depth map can be given to clevar in healpix format. It would be good to add the possibility to also deal with  [healsparse ](https://github.com/LSSTDESC/healsparse) that is the standard DESC format.

**Comment by m-aguena** [comment]
A basic use will be solved in PR #138.
An exploration of using healsparse functionalities will be explored in the future (issue #139 ).
