### ISSUE TITLE
Error instead of warning when no macth

### ISSUE THREAD

**Issue by marina-ricci** [LSSTDESC/clevar#97]
I noticed that when no match are found with the membership method, cat1.mt_input object is empty and then, doing e.g. mt.multiple(cat1,cat2) fails` (TypeError: 'NoneType' object is not subscriptable)`. I think in this case it should return a warning and print that 0 match are found.

**Comment by m-aguena** [comment]
Thanks for letting me know. You are great at finding defects on code :)
